### PR TITLE
Ar/fix google books

### LINKED ISSUE #47: BE - Users show up even if copy is borrowed
If multiple users own a book, all users still show up in the book owners sections even if some of those copies are unavailable.

### LINKED ISSUE #48: BE - 500 error if no results from googlebooks search
Add error handling on BE for if google books service doesn't return results

### PR DESCRIPTION
**Pull request by amikaross**
Type of change

    [] New feature
    [x] Bug Fix

Implements/Fixes:

    - update googlebooks to handle searches that don't return results.
    - Limit users shown for book type to those where the book is currently available.

Neccesary checkmarks:

    [x] All Tests are Passing
    [x] The code will run locally

Check the correct boxes

    [x] This broke nothing
    [] This broke some stuff
    [] This broke everything

Testing Changes

    [] No Tests have been changed
    [x] Some Tests have been changed
    [] All of the Tests have been changed(Please describe what in the world happened)

Checklist:

    [x] My code has no unused/commented out code
    [x] I have reviewed my code
    [x] I have commented my code, particularly in hard-to-understand areas
    [x] I have fully tested my code

GIF ME

### CODE REVIEW

File: app/services/google_books_service.rb [hunk 1]
```diff
@@ -11,7 +11,7 @@ def self.search(title)
       req.params['intitle'] = title
     end
     json = JSON.parse(response.body, symbolize_names: true)
-    json[:items].map { |book| select_data(book) }
+    json[:items] ? json[:items].map { |book| select_data(book) } : []
```
Comment (naomiyocum) [inline app/services/google_books_service.rb:14]: I understand ternary operators so well now after this project

**Review by naomiyocum — APPROVED** [review]
